---
abstract: 'The ISC License'
author:
  - 'David Zurborg <zurborg@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.143240'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Software-License-ISC
requires:
  Software::License: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/zurborg/libsoftware-license-isc-perl/issues
  repository: https://github.com/zurborg/libsoftware-license-isc-perl.git
version: '0.001'
